### ISSUE TITLE
Provide example input & output

### ISSUE THREAD

**Issue by nmz787-intel** [rodv92/PLETSC#1]
I know I could just download and try it... but it would be easier to just see some quick examples in the README.

For example I can't tell if the output is also ASCII/UTF8/UNICODE.

**Comment by rodv92** [comment]
Adding the following to README.MD :

Syntax for compression :

python3 dicstrv.py -c <txt_inputfile> <compressed_outputfile>
Reads txt_inputfile and writes compressed text stream to compressed_outputfile.

If the txt_inputfile is detected as UTF-8 it is converted to ASCII, obviously there will be issues if it uses characters
codes not in the ASCII namespace. Full UTF-8 support is not yet implemented.
If the txt_inputfile is detected as ASCII, no conversion is done.

compressed_outputfile is a binary file (non human readable)

python3 dicstrv.py -c <txt_inputfile>
Reads txt_input file and writes compressed output to stdout.
Same ASCII/UTF-8 handling rules apply (as specified above)

Syntax for decompression :

python3 dicstrv.py -x <compressed_inputfile> <txt_outputfile>
Reads compressed_inputfile and writes cleartext to txt_outputfile.
txt_outputfile is ASCII encoded.

python3 dicstrv.py -x <compressed_inputfile>

Reads compressed_input file and writes cleartext output to stdout
stdout output is ASCII encoded.

**NOTE: dictionary file count1_w.txt and outngrams.bin must be in the same directory as the script.**
**These files are inside the dics.zip archive**

**Comment by rodv92** [comment]
For now input is ASCII only and outputs ASCII only.

For UTF-8 mostly english texts, I'll probably add a conversion back to ASCII with encoding of non ASCII chars in an escaped representation. such as \ux<16 bit binary code> that would be potentially stored in a utf-8 char session dictionary in the case of repeating such utf-8 chars in the stream. this session dic would be limited to 256 entries however, providing modest compression (reducing 16 bit to 8 bit)
